#!/usr/bin/env bash
set -e
export PGPASSWORD=$POSTGRES_PASSWORD;
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
  CREATE USER $APP_DB_WRITE_USER WITH PASSWORD '$APP_DB_WRITE_PASS';
  CREATE USER $APP_DB_READ_USER WITH PASSWORD '$APP_DB_READ_PASS';
  CREATE USER $APP_DB_OPS_USER WITH PASSWORD '$APP_DB_OPS_PASS';
  CREATE DATABASE $APP_DB_NAME;
  GRANT ALL PRIVILEGES ON DATABASE $APP_DB_NAME TO $APP_DB_WRITE_USER;
  \connect $APP_DB_NAME $APP_DB_WRITE_USER
  BEGIN;
    CREATE SCHEMA IF NOT EXISTS kitt;
  COMMIT;
EOSQL
